//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PaymentExample.tr.com.ew.dmzws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TurkPos WS TESTSoap", Namespace="https://turkpos.com.tr/")]
    public partial class TurkPosWSTEST : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BIN_SanalPosOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Ozel_Oran_ListeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Ozel_Oran_SK_ListeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Ozel_Oran_SK_GuncelleOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Islem_Dekont_GonderOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Islem_Odeme_WNSOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Islem_OdemeOperationCompleted;
        
        private System.Threading.SendOrPostCallback KK_SaklamaOperationCompleted;
        
        private System.Threading.SendOrPostCallback KK_Sakli_ListeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Islem_Odeme_WKSOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Islem_SorgulamaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Mutabakat_OzetOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Islem_Iptal_IadeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TP_Islem_Iptal_Iade_KismiOperationCompleted;
        
        private System.Threading.SendOrPostCallback SHA2B64OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TurkPosWSTEST() {
            this.Url = global::PaymentExample.Properties.Settings.Default.PaymentExample_tr_com_ew_dmzws_TurkPos_x0020_WS_x0020_TEST;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BIN_SanalPosCompletedEventHandler BIN_SanalPosCompleted;
        
        /// <remarks/>
        public event TP_Ozel_Oran_ListeCompletedEventHandler TP_Ozel_Oran_ListeCompleted;
        
        /// <remarks/>
        public event TP_Ozel_Oran_SK_ListeCompletedEventHandler TP_Ozel_Oran_SK_ListeCompleted;
        
        /// <remarks/>
        public event TP_Ozel_Oran_SK_GuncelleCompletedEventHandler TP_Ozel_Oran_SK_GuncelleCompleted;
        
        /// <remarks/>
        public event TP_Islem_Dekont_GonderCompletedEventHandler TP_Islem_Dekont_GonderCompleted;
        
        /// <remarks/>
        public event TP_Islem_Odeme_WNSCompletedEventHandler TP_Islem_Odeme_WNSCompleted;
        
        /// <remarks/>
        public event TP_Islem_OdemeCompletedEventHandler TP_Islem_OdemeCompleted;
        
        /// <remarks/>
        public event KK_SaklamaCompletedEventHandler KK_SaklamaCompleted;
        
        /// <remarks/>
        public event KK_Sakli_ListeCompletedEventHandler KK_Sakli_ListeCompleted;
        
        /// <remarks/>
        public event TP_Islem_Odeme_WKSCompletedEventHandler TP_Islem_Odeme_WKSCompleted;
        
        /// <remarks/>
        public event TP_Islem_SorgulamaCompletedEventHandler TP_Islem_SorgulamaCompleted;
        
        /// <remarks/>
        public event TP_Mutabakat_OzetCompletedEventHandler TP_Mutabakat_OzetCompleted;
        
        /// <remarks/>
        public event TP_Islem_Iptal_IadeCompletedEventHandler TP_Islem_Iptal_IadeCompleted;
        
        /// <remarks/>
        public event TP_Islem_Iptal_Iade_KismiCompletedEventHandler TP_Islem_Iptal_Iade_KismiCompleted;
        
        /// <remarks/>
        public event SHA2B64CompletedEventHandler SHA2B64Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/BIN_SanalPos", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Genel_Sonuc BIN_SanalPos(ST_WS_Guvenlik G, string BIN) {
            object[] results = this.Invoke("BIN_SanalPos", new object[] {
                        G,
                        BIN});
            return ((ST_Genel_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void BIN_SanalPosAsync(ST_WS_Guvenlik G, string BIN) {
            this.BIN_SanalPosAsync(G, BIN, null);
        }
        
        /// <remarks/>
        public void BIN_SanalPosAsync(ST_WS_Guvenlik G, string BIN, object userState) {
            if ((this.BIN_SanalPosOperationCompleted == null)) {
                this.BIN_SanalPosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBIN_SanalPosOperationCompleted);
            }
            this.InvokeAsync("BIN_SanalPos", new object[] {
                        G,
                        BIN}, this.BIN_SanalPosOperationCompleted, userState);
        }
        
        private void OnBIN_SanalPosOperationCompleted(object arg) {
            if ((this.BIN_SanalPosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BIN_SanalPosCompleted(this, new BIN_SanalPosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Ozel_Oran_Liste", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Genel_Sonuc TP_Ozel_Oran_Liste(ST_WS_Guvenlik G, string GUID) {
            object[] results = this.Invoke("TP_Ozel_Oran_Liste", new object[] {
                        G,
                        GUID});
            return ((ST_Genel_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Ozel_Oran_ListeAsync(ST_WS_Guvenlik G, string GUID) {
            this.TP_Ozel_Oran_ListeAsync(G, GUID, null);
        }
        
        /// <remarks/>
        public void TP_Ozel_Oran_ListeAsync(ST_WS_Guvenlik G, string GUID, object userState) {
            if ((this.TP_Ozel_Oran_ListeOperationCompleted == null)) {
                this.TP_Ozel_Oran_ListeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Ozel_Oran_ListeOperationCompleted);
            }
            this.InvokeAsync("TP_Ozel_Oran_Liste", new object[] {
                        G,
                        GUID}, this.TP_Ozel_Oran_ListeOperationCompleted, userState);
        }
        
        private void OnTP_Ozel_Oran_ListeOperationCompleted(object arg) {
            if ((this.TP_Ozel_Oran_ListeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Ozel_Oran_ListeCompleted(this, new TP_Ozel_Oran_ListeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Ozel_Oran_SK_Liste", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Genel_Sonuc TP_Ozel_Oran_SK_Liste(ST_WS_Guvenlik G, string GUID) {
            object[] results = this.Invoke("TP_Ozel_Oran_SK_Liste", new object[] {
                        G,
                        GUID});
            return ((ST_Genel_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Ozel_Oran_SK_ListeAsync(ST_WS_Guvenlik G, string GUID) {
            this.TP_Ozel_Oran_SK_ListeAsync(G, GUID, null);
        }
        
        /// <remarks/>
        public void TP_Ozel_Oran_SK_ListeAsync(ST_WS_Guvenlik G, string GUID, object userState) {
            if ((this.TP_Ozel_Oran_SK_ListeOperationCompleted == null)) {
                this.TP_Ozel_Oran_SK_ListeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Ozel_Oran_SK_ListeOperationCompleted);
            }
            this.InvokeAsync("TP_Ozel_Oran_SK_Liste", new object[] {
                        G,
                        GUID}, this.TP_Ozel_Oran_SK_ListeOperationCompleted, userState);
        }
        
        private void OnTP_Ozel_Oran_SK_ListeOperationCompleted(object arg) {
            if ((this.TP_Ozel_Oran_SK_ListeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Ozel_Oran_SK_ListeCompleted(this, new TP_Ozel_Oran_SK_ListeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Ozel_Oran_SK_Guncelle", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Sonuc TP_Ozel_Oran_SK_Guncelle(ST_WS_Guvenlik G, string GUID, string Ozel_Oran_SK_ID, string MO_1, string MO_2, string MO_3, string MO_4, string MO_5, string MO_6, string MO_7, string MO_8, string MO_9, string MO_10, string MO_11, string MO_12) {
            object[] results = this.Invoke("TP_Ozel_Oran_SK_Guncelle", new object[] {
                        G,
                        GUID,
                        Ozel_Oran_SK_ID,
                        MO_1,
                        MO_2,
                        MO_3,
                        MO_4,
                        MO_5,
                        MO_6,
                        MO_7,
                        MO_8,
                        MO_9,
                        MO_10,
                        MO_11,
                        MO_12});
            return ((ST_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Ozel_Oran_SK_GuncelleAsync(ST_WS_Guvenlik G, string GUID, string Ozel_Oran_SK_ID, string MO_1, string MO_2, string MO_3, string MO_4, string MO_5, string MO_6, string MO_7, string MO_8, string MO_9, string MO_10, string MO_11, string MO_12) {
            this.TP_Ozel_Oran_SK_GuncelleAsync(G, GUID, Ozel_Oran_SK_ID, MO_1, MO_2, MO_3, MO_4, MO_5, MO_6, MO_7, MO_8, MO_9, MO_10, MO_11, MO_12, null);
        }
        
        /// <remarks/>
        public void TP_Ozel_Oran_SK_GuncelleAsync(
                    ST_WS_Guvenlik G, 
                    string GUID, 
                    string Ozel_Oran_SK_ID, 
                    string MO_1, 
                    string MO_2, 
                    string MO_3, 
                    string MO_4, 
                    string MO_5, 
                    string MO_6, 
                    string MO_7, 
                    string MO_8, 
                    string MO_9, 
                    string MO_10, 
                    string MO_11, 
                    string MO_12, 
                    object userState) {
            if ((this.TP_Ozel_Oran_SK_GuncelleOperationCompleted == null)) {
                this.TP_Ozel_Oran_SK_GuncelleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Ozel_Oran_SK_GuncelleOperationCompleted);
            }
            this.InvokeAsync("TP_Ozel_Oran_SK_Guncelle", new object[] {
                        G,
                        GUID,
                        Ozel_Oran_SK_ID,
                        MO_1,
                        MO_2,
                        MO_3,
                        MO_4,
                        MO_5,
                        MO_6,
                        MO_7,
                        MO_8,
                        MO_9,
                        MO_10,
                        MO_11,
                        MO_12}, this.TP_Ozel_Oran_SK_GuncelleOperationCompleted, userState);
        }
        
        private void OnTP_Ozel_Oran_SK_GuncelleOperationCompleted(object arg) {
            if ((this.TP_Ozel_Oran_SK_GuncelleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Ozel_Oran_SK_GuncelleCompleted(this, new TP_Ozel_Oran_SK_GuncelleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Islem_Dekont_Gonder", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Sonuc TP_Islem_Dekont_Gonder(ST_WS_Guvenlik G, string GUID, string Dekont_ID, string E_Posta) {
            object[] results = this.Invoke("TP_Islem_Dekont_Gonder", new object[] {
                        G,
                        GUID,
                        Dekont_ID,
                        E_Posta});
            return ((ST_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Islem_Dekont_GonderAsync(ST_WS_Guvenlik G, string GUID, string Dekont_ID, string E_Posta) {
            this.TP_Islem_Dekont_GonderAsync(G, GUID, Dekont_ID, E_Posta, null);
        }
        
        /// <remarks/>
        public void TP_Islem_Dekont_GonderAsync(ST_WS_Guvenlik G, string GUID, string Dekont_ID, string E_Posta, object userState) {
            if ((this.TP_Islem_Dekont_GonderOperationCompleted == null)) {
                this.TP_Islem_Dekont_GonderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Islem_Dekont_GonderOperationCompleted);
            }
            this.InvokeAsync("TP_Islem_Dekont_Gonder", new object[] {
                        G,
                        GUID,
                        Dekont_ID,
                        E_Posta}, this.TP_Islem_Dekont_GonderOperationCompleted, userState);
        }
        
        private void OnTP_Islem_Dekont_GonderOperationCompleted(object arg) {
            if ((this.TP_Islem_Dekont_GonderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Islem_Dekont_GonderCompleted(this, new TP_Islem_Dekont_GonderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Islem_Odeme_WNS", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_TP_Islem_Odeme TP_Islem_Odeme_WNS(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KK_Sahibi, 
                    string KK_No, 
                    string KK_SK_Ay, 
                    string KK_SK_Yil, 
                    string KK_CVC, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5) {
            object[] results = this.Invoke("TP_Islem_Odeme_WNS", new object[] {
                        G,
                        SanalPOS_ID,
                        GUID,
                        KK_Sahibi,
                        KK_No,
                        KK_SK_Ay,
                        KK_SK_Yil,
                        KK_CVC,
                        KK_Sahibi_GSM,
                        Hata_URL,
                        Basarili_URL,
                        Siparis_ID,
                        Siparis_Aciklama,
                        Taksit,
                        Islem_Tutar,
                        Toplam_Tutar,
                        Islem_Hash,
                        Islem_Guvenlik_Tip,
                        Islem_ID,
                        IPAdr,
                        Ref_URL,
                        Data1,
                        Data2,
                        Data3,
                        Data4,
                        Data5});
            return ((ST_TP_Islem_Odeme)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Islem_Odeme_WNSAsync(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KK_Sahibi, 
                    string KK_No, 
                    string KK_SK_Ay, 
                    string KK_SK_Yil, 
                    string KK_CVC, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5) {
            this.TP_Islem_Odeme_WNSAsync(G, SanalPOS_ID, GUID, KK_Sahibi, KK_No, KK_SK_Ay, KK_SK_Yil, KK_CVC, KK_Sahibi_GSM, Hata_URL, Basarili_URL, Siparis_ID, Siparis_Aciklama, Taksit, Islem_Tutar, Toplam_Tutar, Islem_Hash, Islem_Guvenlik_Tip, Islem_ID, IPAdr, Ref_URL, Data1, Data2, Data3, Data4, Data5, null);
        }
        
        /// <remarks/>
        public void TP_Islem_Odeme_WNSAsync(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KK_Sahibi, 
                    string KK_No, 
                    string KK_SK_Ay, 
                    string KK_SK_Yil, 
                    string KK_CVC, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5, 
                    object userState) {
            if ((this.TP_Islem_Odeme_WNSOperationCompleted == null)) {
                this.TP_Islem_Odeme_WNSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Islem_Odeme_WNSOperationCompleted);
            }
            this.InvokeAsync("TP_Islem_Odeme_WNS", new object[] {
                        G,
                        SanalPOS_ID,
                        GUID,
                        KK_Sahibi,
                        KK_No,
                        KK_SK_Ay,
                        KK_SK_Yil,
                        KK_CVC,
                        KK_Sahibi_GSM,
                        Hata_URL,
                        Basarili_URL,
                        Siparis_ID,
                        Siparis_Aciklama,
                        Taksit,
                        Islem_Tutar,
                        Toplam_Tutar,
                        Islem_Hash,
                        Islem_Guvenlik_Tip,
                        Islem_ID,
                        IPAdr,
                        Ref_URL,
                        Data1,
                        Data2,
                        Data3,
                        Data4,
                        Data5}, this.TP_Islem_Odeme_WNSOperationCompleted, userState);
        }
        
        private void OnTP_Islem_Odeme_WNSOperationCompleted(object arg) {
            if ((this.TP_Islem_Odeme_WNSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Islem_Odeme_WNSCompleted(this, new TP_Islem_Odeme_WNSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Islem_Odeme", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_TP_Islem_Odeme TP_Islem_Odeme(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KK_Sahibi, 
                    string KK_No, 
                    string KK_SK_Ay, 
                    string KK_SK_Yil, 
                    string KK_CVC, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5) {
            object[] results = this.Invoke("TP_Islem_Odeme", new object[] {
                        G,
                        SanalPOS_ID,
                        GUID,
                        KK_Sahibi,
                        KK_No,
                        KK_SK_Ay,
                        KK_SK_Yil,
                        KK_CVC,
                        KK_Sahibi_GSM,
                        Hata_URL,
                        Basarili_URL,
                        Siparis_ID,
                        Siparis_Aciklama,
                        Taksit,
                        Islem_Tutar,
                        Toplam_Tutar,
                        Islem_Hash,
                        Islem_ID,
                        IPAdr,
                        Ref_URL,
                        Data1,
                        Data2,
                        Data3,
                        Data4,
                        Data5});
            return ((ST_TP_Islem_Odeme)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Islem_OdemeAsync(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KK_Sahibi, 
                    string KK_No, 
                    string KK_SK_Ay, 
                    string KK_SK_Yil, 
                    string KK_CVC, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5) {
            this.TP_Islem_OdemeAsync(G, SanalPOS_ID, GUID, KK_Sahibi, KK_No, KK_SK_Ay, KK_SK_Yil, KK_CVC, KK_Sahibi_GSM, Hata_URL, Basarili_URL, Siparis_ID, Siparis_Aciklama, Taksit, Islem_Tutar, Toplam_Tutar, Islem_Hash, Islem_ID, IPAdr, Ref_URL, Data1, Data2, Data3, Data4, Data5, null);
        }
        
        /// <remarks/>
        public void TP_Islem_OdemeAsync(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KK_Sahibi, 
                    string KK_No, 
                    string KK_SK_Ay, 
                    string KK_SK_Yil, 
                    string KK_CVC, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5, 
                    object userState) {
            if ((this.TP_Islem_OdemeOperationCompleted == null)) {
                this.TP_Islem_OdemeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Islem_OdemeOperationCompleted);
            }
            this.InvokeAsync("TP_Islem_Odeme", new object[] {
                        G,
                        SanalPOS_ID,
                        GUID,
                        KK_Sahibi,
                        KK_No,
                        KK_SK_Ay,
                        KK_SK_Yil,
                        KK_CVC,
                        KK_Sahibi_GSM,
                        Hata_URL,
                        Basarili_URL,
                        Siparis_ID,
                        Siparis_Aciklama,
                        Taksit,
                        Islem_Tutar,
                        Toplam_Tutar,
                        Islem_Hash,
                        Islem_ID,
                        IPAdr,
                        Ref_URL,
                        Data1,
                        Data2,
                        Data3,
                        Data4,
                        Data5}, this.TP_Islem_OdemeOperationCompleted, userState);
        }
        
        private void OnTP_Islem_OdemeOperationCompleted(object arg) {
            if ((this.TP_Islem_OdemeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Islem_OdemeCompleted(this, new TP_Islem_OdemeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/KK_Saklama", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_KK_Saklama KK_Saklama(ST_WS_Guvenlik G, string Kart_No, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_CVV, string Data1, string Data2, string Data3) {
            object[] results = this.Invoke("KK_Saklama", new object[] {
                        G,
                        Kart_No,
                        KK_Sahibi,
                        KK_No,
                        KK_SK_Ay,
                        KK_SK_Yil,
                        KK_CVV,
                        Data1,
                        Data2,
                        Data3});
            return ((ST_KK_Saklama)(results[0]));
        }
        
        /// <remarks/>
        public void KK_SaklamaAsync(ST_WS_Guvenlik G, string Kart_No, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_CVV, string Data1, string Data2, string Data3) {
            this.KK_SaklamaAsync(G, Kart_No, KK_Sahibi, KK_No, KK_SK_Ay, KK_SK_Yil, KK_CVV, Data1, Data2, Data3, null);
        }
        
        /// <remarks/>
        public void KK_SaklamaAsync(ST_WS_Guvenlik G, string Kart_No, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_CVV, string Data1, string Data2, string Data3, object userState) {
            if ((this.KK_SaklamaOperationCompleted == null)) {
                this.KK_SaklamaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKK_SaklamaOperationCompleted);
            }
            this.InvokeAsync("KK_Saklama", new object[] {
                        G,
                        Kart_No,
                        KK_Sahibi,
                        KK_No,
                        KK_SK_Ay,
                        KK_SK_Yil,
                        KK_CVV,
                        Data1,
                        Data2,
                        Data3}, this.KK_SaklamaOperationCompleted, userState);
        }
        
        private void OnKK_SaklamaOperationCompleted(object arg) {
            if ((this.KK_SaklamaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KK_SaklamaCompleted(this, new KK_SaklamaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/KK_Sakli_Liste", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Genel_Sonuc KK_Sakli_Liste(ST_WS_Guvenlik G, string Kart_No, string KS_KK_Kisi_ID) {
            object[] results = this.Invoke("KK_Sakli_Liste", new object[] {
                        G,
                        Kart_No,
                        KS_KK_Kisi_ID});
            return ((ST_Genel_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void KK_Sakli_ListeAsync(ST_WS_Guvenlik G, string Kart_No, string KS_KK_Kisi_ID) {
            this.KK_Sakli_ListeAsync(G, Kart_No, KS_KK_Kisi_ID, null);
        }
        
        /// <remarks/>
        public void KK_Sakli_ListeAsync(ST_WS_Guvenlik G, string Kart_No, string KS_KK_Kisi_ID, object userState) {
            if ((this.KK_Sakli_ListeOperationCompleted == null)) {
                this.KK_Sakli_ListeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKK_Sakli_ListeOperationCompleted);
            }
            this.InvokeAsync("KK_Sakli_Liste", new object[] {
                        G,
                        Kart_No,
                        KS_KK_Kisi_ID}, this.KK_Sakli_ListeOperationCompleted, userState);
        }
        
        private void OnKK_Sakli_ListeOperationCompleted(object arg) {
            if ((this.KK_Sakli_ListeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KK_Sakli_ListeCompleted(this, new KK_Sakli_ListeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Islem_Odeme_WKS", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_TP_Islem_Odeme TP_Islem_Odeme_WKS(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KS_Kart_No, 
                    string KK_GUID, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5) {
            object[] results = this.Invoke("TP_Islem_Odeme_WKS", new object[] {
                        G,
                        SanalPOS_ID,
                        GUID,
                        KS_Kart_No,
                        KK_GUID,
                        KK_Sahibi_GSM,
                        Hata_URL,
                        Basarili_URL,
                        Siparis_ID,
                        Siparis_Aciklama,
                        Taksit,
                        Islem_Tutar,
                        Toplam_Tutar,
                        Islem_Hash,
                        Islem_Guvenlik_Tip,
                        Islem_ID,
                        IPAdr,
                        Ref_URL,
                        Data1,
                        Data2,
                        Data3,
                        Data4,
                        Data5});
            return ((ST_TP_Islem_Odeme)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Islem_Odeme_WKSAsync(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KS_Kart_No, 
                    string KK_GUID, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5) {
            this.TP_Islem_Odeme_WKSAsync(G, SanalPOS_ID, GUID, KS_Kart_No, KK_GUID, KK_Sahibi_GSM, Hata_URL, Basarili_URL, Siparis_ID, Siparis_Aciklama, Taksit, Islem_Tutar, Toplam_Tutar, Islem_Hash, Islem_Guvenlik_Tip, Islem_ID, IPAdr, Ref_URL, Data1, Data2, Data3, Data4, Data5, null);
        }
        
        /// <remarks/>
        public void TP_Islem_Odeme_WKSAsync(
                    ST_WS_Guvenlik G, 
                    int SanalPOS_ID, 
                    string GUID, 
                    string KS_Kart_No, 
                    string KK_GUID, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Hash, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string Data5, 
                    object userState) {
            if ((this.TP_Islem_Odeme_WKSOperationCompleted == null)) {
                this.TP_Islem_Odeme_WKSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Islem_Odeme_WKSOperationCompleted);
            }
            this.InvokeAsync("TP_Islem_Odeme_WKS", new object[] {
                        G,
                        SanalPOS_ID,
                        GUID,
                        KS_Kart_No,
                        KK_GUID,
                        KK_Sahibi_GSM,
                        Hata_URL,
                        Basarili_URL,
                        Siparis_ID,
                        Siparis_Aciklama,
                        Taksit,
                        Islem_Tutar,
                        Toplam_Tutar,
                        Islem_Hash,
                        Islem_Guvenlik_Tip,
                        Islem_ID,
                        IPAdr,
                        Ref_URL,
                        Data1,
                        Data2,
                        Data3,
                        Data4,
                        Data5}, this.TP_Islem_Odeme_WKSOperationCompleted, userState);
        }
        
        private void OnTP_Islem_Odeme_WKSOperationCompleted(object arg) {
            if ((this.TP_Islem_Odeme_WKSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Islem_Odeme_WKSCompleted(this, new TP_Islem_Odeme_WKSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Islem_Sorgulama", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Genel_Sonuc TP_Islem_Sorgulama(ST_WS_Guvenlik G, string GUID, string Dekont_ID, string Siparis_ID, string Islem_ID) {
            object[] results = this.Invoke("TP_Islem_Sorgulama", new object[] {
                        G,
                        GUID,
                        Dekont_ID,
                        Siparis_ID,
                        Islem_ID});
            return ((ST_Genel_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Islem_SorgulamaAsync(ST_WS_Guvenlik G, string GUID, string Dekont_ID, string Siparis_ID, string Islem_ID) {
            this.TP_Islem_SorgulamaAsync(G, GUID, Dekont_ID, Siparis_ID, Islem_ID, null);
        }
        
        /// <remarks/>
        public void TP_Islem_SorgulamaAsync(ST_WS_Guvenlik G, string GUID, string Dekont_ID, string Siparis_ID, string Islem_ID, object userState) {
            if ((this.TP_Islem_SorgulamaOperationCompleted == null)) {
                this.TP_Islem_SorgulamaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Islem_SorgulamaOperationCompleted);
            }
            this.InvokeAsync("TP_Islem_Sorgulama", new object[] {
                        G,
                        GUID,
                        Dekont_ID,
                        Siparis_ID,
                        Islem_ID}, this.TP_Islem_SorgulamaOperationCompleted, userState);
        }
        
        private void OnTP_Islem_SorgulamaOperationCompleted(object arg) {
            if ((this.TP_Islem_SorgulamaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Islem_SorgulamaCompleted(this, new TP_Islem_SorgulamaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Mutabakat_Ozet", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Genel_Sonuc TP_Mutabakat_Ozet(ST_WS_Guvenlik G, string GUID, string Tarih_Bas, string Tarih_Bit) {
            object[] results = this.Invoke("TP_Mutabakat_Ozet", new object[] {
                        G,
                        GUID,
                        Tarih_Bas,
                        Tarih_Bit});
            return ((ST_Genel_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Mutabakat_OzetAsync(ST_WS_Guvenlik G, string GUID, string Tarih_Bas, string Tarih_Bit) {
            this.TP_Mutabakat_OzetAsync(G, GUID, Tarih_Bas, Tarih_Bit, null);
        }
        
        /// <remarks/>
        public void TP_Mutabakat_OzetAsync(ST_WS_Guvenlik G, string GUID, string Tarih_Bas, string Tarih_Bit, object userState) {
            if ((this.TP_Mutabakat_OzetOperationCompleted == null)) {
                this.TP_Mutabakat_OzetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Mutabakat_OzetOperationCompleted);
            }
            this.InvokeAsync("TP_Mutabakat_Ozet", new object[] {
                        G,
                        GUID,
                        Tarih_Bas,
                        Tarih_Bit}, this.TP_Mutabakat_OzetOperationCompleted, userState);
        }
        
        private void OnTP_Mutabakat_OzetOperationCompleted(object arg) {
            if ((this.TP_Mutabakat_OzetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Mutabakat_OzetCompleted(this, new TP_Mutabakat_OzetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Islem_Iptal_Iade", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Sonuc TP_Islem_Iptal_Iade(ST_WS_Guvenlik G, string GUID, string Durum, string Dekont_ID) {
            object[] results = this.Invoke("TP_Islem_Iptal_Iade", new object[] {
                        G,
                        GUID,
                        Durum,
                        Dekont_ID});
            return ((ST_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Islem_Iptal_IadeAsync(ST_WS_Guvenlik G, string GUID, string Durum, string Dekont_ID) {
            this.TP_Islem_Iptal_IadeAsync(G, GUID, Durum, Dekont_ID, null);
        }
        
        /// <remarks/>
        public void TP_Islem_Iptal_IadeAsync(ST_WS_Guvenlik G, string GUID, string Durum, string Dekont_ID, object userState) {
            if ((this.TP_Islem_Iptal_IadeOperationCompleted == null)) {
                this.TP_Islem_Iptal_IadeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Islem_Iptal_IadeOperationCompleted);
            }
            this.InvokeAsync("TP_Islem_Iptal_Iade", new object[] {
                        G,
                        GUID,
                        Durum,
                        Dekont_ID}, this.TP_Islem_Iptal_IadeOperationCompleted, userState);
        }
        
        private void OnTP_Islem_Iptal_IadeOperationCompleted(object arg) {
            if ((this.TP_Islem_Iptal_IadeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Islem_Iptal_IadeCompleted(this, new TP_Islem_Iptal_IadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/TP_Islem_Iptal_Iade_Kismi", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Sonuc TP_Islem_Iptal_Iade_Kismi(ST_WS_Guvenlik G, string GUID, string Durum, string Dekont_ID, double Tutar) {
            object[] results = this.Invoke("TP_Islem_Iptal_Iade_Kismi", new object[] {
                        G,
                        GUID,
                        Durum,
                        Dekont_ID,
                        Tutar});
            return ((ST_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void TP_Islem_Iptal_Iade_KismiAsync(ST_WS_Guvenlik G, string GUID, string Durum, string Dekont_ID, double Tutar) {
            this.TP_Islem_Iptal_Iade_KismiAsync(G, GUID, Durum, Dekont_ID, Tutar, null);
        }
        
        /// <remarks/>
        public void TP_Islem_Iptal_Iade_KismiAsync(ST_WS_Guvenlik G, string GUID, string Durum, string Dekont_ID, double Tutar, object userState) {
            if ((this.TP_Islem_Iptal_Iade_KismiOperationCompleted == null)) {
                this.TP_Islem_Iptal_Iade_KismiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTP_Islem_Iptal_Iade_KismiOperationCompleted);
            }
            this.InvokeAsync("TP_Islem_Iptal_Iade_Kismi", new object[] {
                        G,
                        GUID,
                        Durum,
                        Dekont_ID,
                        Tutar}, this.TP_Islem_Iptal_Iade_KismiOperationCompleted, userState);
        }
        
        private void OnTP_Islem_Iptal_Iade_KismiOperationCompleted(object arg) {
            if ((this.TP_Islem_Iptal_Iade_KismiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TP_Islem_Iptal_Iade_KismiCompleted(this, new TP_Islem_Iptal_Iade_KismiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpos.com.tr/SHA2B64", RequestNamespace="https://turkpos.com.tr/", ResponseNamespace="https://turkpos.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SHA2B64(string Data) {
            object[] results = this.Invoke("SHA2B64", new object[] {
                        Data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SHA2B64Async(string Data) {
            this.SHA2B64Async(Data, null);
        }
        
        /// <remarks/>
        public void SHA2B64Async(string Data, object userState) {
            if ((this.SHA2B64OperationCompleted == null)) {
                this.SHA2B64OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSHA2B64OperationCompleted);
            }
            this.InvokeAsync("SHA2B64", new object[] {
                        Data}, this.SHA2B64OperationCompleted, userState);
        }
        
        private void OnSHA2B64OperationCompleted(object arg) {
            if ((this.SHA2B64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SHA2B64Completed(this, new SHA2B64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpos.com.tr/")]
    public partial class ST_WS_Guvenlik {
        
        private string cLIENT_CODEField;
        
        private string cLIENT_USERNAMEField;
        
        private string cLIENT_PASSWORDField;
        
        /// <remarks/>
        public string CLIENT_CODE {
            get {
                return this.cLIENT_CODEField;
            }
            set {
                this.cLIENT_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string CLIENT_USERNAME {
            get {
                return this.cLIENT_USERNAMEField;
            }
            set {
                this.cLIENT_USERNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CLIENT_PASSWORD {
            get {
                return this.cLIENT_PASSWORDField;
            }
            set {
                this.cLIENT_PASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpos.com.tr/")]
    public partial class ST_KK_Saklama {
        
        private string gUIDField;
        
        private string sonucField;
        
        private string sonuc_StrField;
        
        /// <remarks/>
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc_Str {
            get {
                return this.sonuc_StrField;
            }
            set {
                this.sonuc_StrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpos.com.tr/")]
    public partial class ST_TP_Islem_Odeme {
        
        private long islem_IDField;
        
        private string uCD_URLField;
        
        private string sonucField;
        
        private string sonuc_StrField;
        
        /// <remarks/>
        public long Islem_ID {
            get {
                return this.islem_IDField;
            }
            set {
                this.islem_IDField = value;
            }
        }
        
        /// <remarks/>
        public string UCD_URL {
            get {
                return this.uCD_URLField;
            }
            set {
                this.uCD_URLField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc_Str {
            get {
                return this.sonuc_StrField;
            }
            set {
                this.sonuc_StrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpos.com.tr/")]
    public partial class ST_Sonuc {
        
        private string sonucField;
        
        private string sonuc_StrField;
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc_Str {
            get {
                return this.sonuc_StrField;
            }
            set {
                this.sonuc_StrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpos.com.tr/")]
    public partial class ST_Genel_Sonuc {
        
        private System.Data.DataTable dT_BilgiField;
        
        private string sonucField;
        
        private string sonuc_StrField;
        
        /// <remarks/>
        public System.Data.DataTable DT_Bilgi {
            get {
                return this.dT_BilgiField;
            }
            set {
                this.dT_BilgiField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc_Str {
            get {
                return this.sonuc_StrField;
            }
            set {
                this.sonuc_StrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void BIN_SanalPosCompletedEventHandler(object sender, BIN_SanalPosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BIN_SanalPosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BIN_SanalPosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Genel_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Genel_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Ozel_Oran_ListeCompletedEventHandler(object sender, TP_Ozel_Oran_ListeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Ozel_Oran_ListeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Ozel_Oran_ListeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Genel_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Genel_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Ozel_Oran_SK_ListeCompletedEventHandler(object sender, TP_Ozel_Oran_SK_ListeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Ozel_Oran_SK_ListeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Ozel_Oran_SK_ListeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Genel_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Genel_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Ozel_Oran_SK_GuncelleCompletedEventHandler(object sender, TP_Ozel_Oran_SK_GuncelleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Ozel_Oran_SK_GuncelleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Ozel_Oran_SK_GuncelleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Islem_Dekont_GonderCompletedEventHandler(object sender, TP_Islem_Dekont_GonderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Islem_Dekont_GonderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Islem_Dekont_GonderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Islem_Odeme_WNSCompletedEventHandler(object sender, TP_Islem_Odeme_WNSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Islem_Odeme_WNSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Islem_Odeme_WNSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_TP_Islem_Odeme Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_TP_Islem_Odeme)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Islem_OdemeCompletedEventHandler(object sender, TP_Islem_OdemeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Islem_OdemeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Islem_OdemeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_TP_Islem_Odeme Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_TP_Islem_Odeme)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KK_SaklamaCompletedEventHandler(object sender, KK_SaklamaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KK_SaklamaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KK_SaklamaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_KK_Saklama Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_KK_Saklama)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KK_Sakli_ListeCompletedEventHandler(object sender, KK_Sakli_ListeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KK_Sakli_ListeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KK_Sakli_ListeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Genel_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Genel_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Islem_Odeme_WKSCompletedEventHandler(object sender, TP_Islem_Odeme_WKSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Islem_Odeme_WKSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Islem_Odeme_WKSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_TP_Islem_Odeme Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_TP_Islem_Odeme)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Islem_SorgulamaCompletedEventHandler(object sender, TP_Islem_SorgulamaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Islem_SorgulamaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Islem_SorgulamaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Genel_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Genel_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Mutabakat_OzetCompletedEventHandler(object sender, TP_Mutabakat_OzetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Mutabakat_OzetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Mutabakat_OzetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Genel_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Genel_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Islem_Iptal_IadeCompletedEventHandler(object sender, TP_Islem_Iptal_IadeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Islem_Iptal_IadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Islem_Iptal_IadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TP_Islem_Iptal_Iade_KismiCompletedEventHandler(object sender, TP_Islem_Iptal_Iade_KismiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TP_Islem_Iptal_Iade_KismiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TP_Islem_Iptal_Iade_KismiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SHA2B64CompletedEventHandler(object sender, SHA2B64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SHA2B64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SHA2B64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591